[package]
name = "chromplotter"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
plotters = "0.3.7"
polars = {version = "0.45.1", features = ["lazy"] }